name: Production Deploy

on:
  workflow_dispatch:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure a tag was selected
        run: |
          echo ${{github.ref_name}}
